# Generated by Django 4.1 on 2023-06-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_comment_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.category"
            ),
        ),
    ]
